config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  
  resources :trainings, only: [:index, :new, :create]
  root "trainings#index"

  put 'users/follow/:user_id',to: 'users#follow'
  put 'users/unfollow/:user_id',to: 'users#unfollow'
  get 'users/follow_list/:user_id',to: 'users#follow_list'
  get 'users/follower_list/:user_id',to:'users#follower_list'
  # フォロー・フォロワーの一覧ページ
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :arm
    validates :spine
    validates :abs
    validates :leg
  end

  with_options format: { with: /\A[0-9]+\z/, message: "半角数字で入力してください"} do
    validates :arm
    validates :spine
    validates :abs
    validates :leg
  end

  with_options numericality: { greater_than_or_equal_to: 0} do
    validates :arm
    validates :spine
    validates :abs
    validates :leg
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def index
    if user_signed_in?
      range=Range.new(Time.zone.today, Time.zone.today.tomorrow)
      @trainings = Training.where(created_at: range, user_id: current_user.id)
      @data = {'腕筋' => @trainings.sum(:arm) , '背筋' => @trainings.sum(:spine), '腹筋' => @trainings.sum(:abs),  '脚筋' => @trainings.sum(:leg)}

      range2=Range.new(Time.zone.today.ago(6.days),Time.zone.tomorrow)
      @trainings2 = Training.where(created_at: range2, user_id: current_user.id)
      @data2 = {'腕筋' => @trainings2.sum(:arm) , '背筋' => @trainings2.sum(:spine), '腹筋' => @trainings2.sum(:abs),  '脚筋' => @trainings2.sum(:leg)}
      

      range3=Range.new(Time.zone.today,Time.zone.tomorrow)
      @trainings3 = Training.where(created_at: range3,user_id: current_user.id)
      @total1 = @trainings3.sum(:arm) + @trainings3.sum(:spine) + @trainings3.sum(:abs) + @trainings3.sum(:leg)

      range4=Range.new(Time.zone.today.ago(1.days),Time.zone.today)
      @trainings4 = Training.where(created_at: range4,user_id: current_user.id)
      @total2 = @trainings4.sum(:arm) + @trainings4.sum(:spine) + @trainings4.sum(:abs) + @trainings4.sum(:leg)

      range5=Range.new(Time.zone.today.ago(2.days),Time.zone.today.ago(1.days))
      @trainings5 = Training.where(created_at: range5,user_id: current_user.id)
      @total3 = @trainings5.sum(:arm) + @trainings5.sum(:spine) + @trainings5.sum(:abs) + @trainings5.sum(:leg)

      range6=Range.new(Time.zone.today.ago(3.days),Time.zone.today.ago(2.days))
      @trainings6 = Training.where(created_at: range6,user_id: current_user.id)
      @total4 = @trainings6.sum(:arm) + @trainings6.sum(:spine) + @trainings6.sum(:abs) + @trainings6.sum(:leg)

      range7=Range.new(Time.zone.today.ago(4.days),Time.zone.today.ago(3.days))
      @trainings7 = Training.where(created_at: range7,user_id: current_user.id)
      @total5 = @trainings7.sum(:arm) + @trainings7.sum(:spine) + @trainings7.sum(:abs) + @trainings7.sum(:leg)

      range8=Range.new(Time.zone.today.ago(5.days),Time.zone.today.ago(4.days))
      @trainings8 = Training.where(created_at: range8,user_id: current_user.id)
      @total6 = @trainings8.sum(:arm) + @trainings8.sum(:spine) + @trainings8.sum(:abs) + @trainings8.sum(:leg)

      range9=Range.new(Time.zone.today.ago(6.days),Time.zone.today.ago(5.days))
      @trainings9 = Training.where(created_at: range9,user_id: current_user.id)
      @total7 = @trainings9.sum(:arm) + @trainings9.sum(:spine) + @trainings9.sum(:abs) + @trainings9.sum(:leg)
      
      @data3 = {Time.zone.today.ago(6.days).strftime('%Y年%m月%d日') => @total7,Time.zone.today.ago(5.days).strftime('%Y年%m月%d日') => @total6,
                Time.zone.today.ago(4.days).strftime('%Y年%m月%d日') => @total5,Time.zone.today.ago(3.days).strftime('%Y年%m月%d日') => @total4,
                Time.zone.today.ago(2.days).strftime('%Y年%m月%d日') => @total3,Time.zone.today.ago(1.days).strftime('%Y年%m月%d日') => @total2,
                Time.zone.today.strftime('%Y年%m月%d日') => @total1 }

      
      @follows = current_user.all_following
      @num = 0
      @f_datas = []

      @follows.each do |follow|
        f_trainings1 = Training.where(created_at: range3, user_id: follow)
        f_total1 = f_trainings1.sum(:arm) + f_trainings1.sum(:spine) + f_trainings1.sum(:abs) + f_trainings1.sum(:leg)

        f_trainings2 = Training.where(created_at: range4, user_id: follow)
        f_total2 = f_trainings2.sum(:arm) + f_trainings2.sum(:spine) + f_trainings2.sum(:abs) + f_trainings2.sum(:leg)

        f_trainings3 = Training.where(created_at: range5, user_id: follow)
        f_total3 = f_trainings3.sum(:arm) + f_trainings3.sum(:spine) + f_trainings3.sum(:abs) + f_trainings3.sum(:leg)

        f_trainings4 = Training.where(created_at: range6, user_id: follow)
        f_total4 = f_trainings4.sum(:arm) + f_trainings4.sum(:spine) + f_trainings4.sum(:abs) + f_trainings4.sum(:leg)

        f_trainings5 = Training.where(created_at: range7, user_id: follow)
        f_total5 = f_trainings5.sum(:arm) + f_trainings5.sum(:spine) + f_trainings5.sum(:abs) + f_trainings5.sum(:leg)

        f_trainings6 = Training.where(created_at: range8, user_id: follow)
        f_total6 = f_trainings6.sum(:arm) + f_trainings6.sum(:spine) + f_trainings6.sum(:abs) + f_trainings6.sum(:leg)

        f_trainings7 = Training.where(created_at: range9, user_id: follow)
        f_total7 = f_trainings7.sum(:arm) + f_trainings7.sum(:spine) + f_trainings7.sum(:abs) + f_trainings7.sum(:leg)

        @f_datas << {Time.zone.today.ago(6.days).strftime('%Y年%m月%d日') => f_total7,Time.zone.today.ago(5.days).strftime('%Y年%m月%d日') => f_total6,
                    Time.zone.today.ago(4.days).strftime('%Y年%m月%d日') => f_total5,Time.zone.today.ago(3.days).strftime('%Y年%m月%d日') => f_total4,
                    Time.zone.today.ago(2.days).strftime('%Y年%m月%d日') => f_total3,Time.zone.today.ago(1.days).strftime('%Y年%m月%d日') => f_total2,
                    Time.zone.today.strftime('%Y年%m月%d日') => f_total1 }
      end
    end
  end 

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      render :create
    else
      render :new
    end
  end

  private

  def training_params
    params.require(:training).permit(:arm, :spine, :abs, :leg).merge(user_id: current_user.id)
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/create.html.erb
<div class="create-wrapper"></div>

  <%= render "shared/navbar"%>
  
  <div class='create-main'>
    <div class="comments">
      
      <div class='a-word'>
        <h1 class='good-job'>
        Good Job!!!
        </h1>
        <h2 class='lets-eat'>
        ~~30分以内にタンパク質を摂取しましょう！~~
        </h2>
      </div>

      <div class='description-contents'>
        <h2 class=about-protein>
        ＜タンパク質に関して＞
        </h2>
        <div class='description'>
        タンパク質と聞くと『プロテイン』が思い浮かぶのではないでしょうか。しかしプロテインは安くても月々3000円程度、こだわるならば軽く1万円は超えます。「そんなに高いお金払えない」といった悩みに応えてコスパ最強最高のプロテインをご紹介致します。それは<strong class='protein-food'>『納豆卵かけご飯』</strong>です。卵と納豆はご飯にかけると1食20g近くタンパク質を摂取できその含有量はプロテインドリンク1杯分にも引けを取りません。しかも卵1個20円、納豆1個30円、ご飯1杯40円と仮定しても1回90円ですし、プロテインと異なり食事として生活に組み込むことができます。また、タンパク質はトレーニング後30分以内に摂取することで身体への吸収が効率的になります。みなさんもぜひお試しあれ！
        </div>
      </div>

      <div class='description-contents'>
        <h2 class='about-protein'>
        ＜高タンパクな食材＞
        </h2>
        <div class='description'>
        鶏の胸肉、鶏のささみ、生ハム、牛もも肉、ローストビーフ、いわし丸干し、たらこ、スルメ、卵、納豆、きな粉、油揚げ、プロセスチーズ etc...
        </div>
      </div>

      <%=link_to(trainings_path) do %>
        <button class="to-home" >トップへ戻る</button>
      <%end%>

      <div class='space'></div>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/trainings/index.html.erb
<div class="first-page-wrapper">

  <%= render "shared/navbar"%>

  <% if user_signed_in? %> 
    <%= render "shared/home"%> 
  <%else%> 
    <%= render "shared/top"%>
  <%end%> 
</div>

<%= render "shared/footer"%>

app/views/trainings/new.html.erb
<div class="training-wrapper">

  <%= render "shared/navbar"%>

  <div class='t-boxes'>
    <div class="t-inner">

      <%= form_with model: @training, url:trainings_path, local: true do |f| %>
        <h1 class="t-title">Trainig</h1>

        <div class="box-arm">
          <h4 class="t-part">腕筋</h4>
          <div class="counter"><%= f.number_field :arm, class:"detail-counter", placeholder:"回数を入力してください (半角数字 /必須)"%></div>
        </div>

        <div class="box-spine">
          <h4 class="t-part">背筋</h4>
          <div class="counter"><%= f.number_field :spine, class:"detail-counter", placeholder:"回数を入力してください (半角数字 /必須)"%></div>
        </div>

        <div class="box-abs">
          <h4 class="t-part">腹筋</h4>
          <div class="counter"><%= f.number_field :abs, class:"detail-counter", placeholder:"回数を入力してください (半角数字 /必須)"%></div>
        </div>

        <div class="box-leg">
          <h4 class="t-part">脚筋</h4>
          <div class="counter"><%= f.number_field :leg, class:"detail-counter", placeholder:"回数を入力してください (半角数字 /必須)"%></div>
        </div>


        <%# 終了ボタン %>
        <div class="box-finish">
          <%= f.submit "Finish" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>