config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  
  resources :trainings, only: [:index, :new, :create]
  root "trainings#index"

  put 'users/follow/:user_id',to: 'users#follow'
  put 'users/unfollow/:user_id',to: 'users#unfollow'
  get 'users/follow_list/:user_id',to: 'users#follow_list'
  get 'users/follower_list/:user_id',to:'users#follower_list'
  # フォロー・フォロワーの一覧ページ
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trainings
  has_one_attached :image
  
  acts_as_followable
  acts_as_follower

  with_options uniqueness: true do
    validates :nickname,presence: true
    validates :email
  end

  def self.search(search)
    if search != ""
      User.where('nickname LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
 
    if resource.update_without_current_password(account_update_params)
      yield resource if block_given?
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end

  # def after_update_path_for(resource)
  #   user_path(current_user)
  # end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(nickname: "DESC")
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_to user_path(@user)
  end
#フォローする

  def unfollow
      @user = User.find(params[:user_id])
      current_user.stop_following(@user)
      redirect_to user_path(@user)
  end
  #フォローを外す


  def follow_list
    @user = User.find(params[:user_id])
  end
  #フォローしてる人の一覧ページ

  def follower_list
    @user = User.find(params[:user_id])
  end
  #フォロワーの一覧ページ
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(nickname: "DESC")
  end

  def show
  end

  def search
    @users = User.search(params[:keyword])
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_to users_path
  end
  #フォローする

  def unfollow
      @user = User.find(params[:user_id])
      current_user.stop_following(@user)
      redirect_to users_path
  end
  #フォローを外す


  def follow_list
    @users = User.find(params[:user_id])
  end
  #フォローしてる人の一覧ページ

  def follower_list
    @user = User.find(params[:user_id])
  end
  #フォロワーの一覧ページ
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/follow_list.html.erb
<div class='friends-wrapper'>

  <%= render "shared/navbar"%>

  <div class='friends-main'>
    <h1 class='my-name'>フォロー</h1>
    <div class='my-friends-data'>
      <h2><%= link_to 'フォロー数', {controller: :users,action: :follow_list,user_id: current_user.id}, class: "follow-path" %>:<%= current_user.follow_count %>　</h2>
      <h2><%= link_to 'フォロワー数', {controller: :users,action: :follower_list,user_id: current_user.id}, class: "follower-path" %>:<%= current_user.followers_count %></h2>
    </div>

    <div class='search-box'>
      <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "ユーザー名を検索する", class: "search-input" %>
        <%= form.submit "Search", class: "search-btn" %>
      <% end %>
    </div>

    <div class='all-user'>
      <% current_user.all_following.each do |user| %>
        <% if user.id != current_user.id %>
          <div class='each-user'>
            <div class='left-box'>
              <div class='user-img'>
                <%if user.image.present? %>
                  <%= image_tag user.image, class: 'friends-img' %>
                <%else %>
                  <img class='friends-img'>
                <%end %>
              </div>
              <div class='user-name'><%= user.nickname %></div>
            </div>

            <div class='rigth-box'>
              <div class="follow_form">
                <% if current_user.following? user %>
                  <button class="unfollow-btn">
                    <%= link_to "Following", {controller: :users,action: :unfollow,user_id: user.id}, method: :put, class:"unfollow"%>
                  </button>
                <% else %>
                  <button class="follow-btn">
                    <%= link_to "Follow", {controller: :users,action: :follow,user_id: user.id}, method: :put, class:"follow"%>
                  </button>
                <% end %>
              </div>
            </div>
          </div>
        <%end%>
      <% end %>
    </div>

  </div>
</div>

<%= render "shared/footer"%>

app/views/users/follower_list.html.erb
<div class='friends-wrapper'>

  <%= render "shared/navbar"%>

  <div class='friends-main'>
    <h1 class='my-name'>フォロワー</h1>
    <div class='my-friends-data'>
      <h2><%= link_to 'フォロー数', {controller: :users,action: :follow_list,user_id: current_user.id}, class: "follow-path" %>:<%= current_user.follow_count %>　</h2>
      <h2><%= link_to 'フォロワー数', {controller: :users,action: :follower_list,user_id: current_user.id}, class: "follower-path" %>:<%= current_user.followers_count %></h2>
    </div>

    <div class='search-box'>
      <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "ユーザー名を検索する", class: "search-input" %>
        <%= form.submit "Search", class: "search-btn" %>
      <% end %>
    </div>

    <div class='all-user'>
      <% current_user.followers.each do |user| %>
        <% if user.id != current_user.id %>
          <div class='each-user'>
            <div class='left-box'>
              <div class='user-img'>
                <%if user.image.present? %>
                  <%= image_tag user.image, class: 'friends-img' %>
                <%else %>
                  <img class='friends-img'>
                <%end %>
              </div>
              <div class='user-name'><%= user.nickname %></div>
            </div>

            <div class='rigth-box'>
              <div class="follow_form">
                <% if current_user.following? user %>
                  <button class="unfollow-btn">
                    <%= link_to "Following", {controller: :users,action: :unfollow,user_id: user.id}, method: :put, class:"unfollow"%>
                  </button>
                <% else %>
                  <button class="follow-btn">
                    <%= link_to "Follow", {controller: :users,action: :follow,user_id: user.id}, method: :put, class:"follow"%>
                  </button>
                <% end %>
              </div>
            </div>
          </div>
        <%end%>
      <% end %>
    </div>

  </div>
</div>

<%= render "shared/footer"%>

app/views/users/index.html.erb
<div class='friends-wrapper'>

  <%= render "shared/navbar"%>

  <div class='friends-main'>
    <h1 class='my-name'><%= current_user.nickname %></h1>
    <div class='my-friends-data'>
      <h2><%= link_to 'フォロー数', {controller: :users,action: :follow_list,user_id: current_user.id}, class: "follow-path" %>:<%= current_user.follow_count %>　</h2>
      <h2><%= link_to 'フォロワー数', {controller: :users,action: :follower_list,user_id: current_user.id}, class: "follower-path" %>:<%= current_user.followers_count %></h2>
    </div>

    <div class='search-box'>
      <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "ユーザー名を検索する", class: "search-input" %>
        <%= form.submit "Search", class: "search-btn" %>
      <% end %>
    </div>

    <div class='all-user'>
      <% @users.each do |user|%>
        <% if user.id != current_user.id %>
          <div class='each-user'>
            <div class='left-box'>
              <div class='user-img'>
                <%if user.image.present? %>
                  <%= image_tag user.image, class: 'friends-img' %>
                <%else %>
                  <img class='friends-img'>
                <%end %>
              </div>
              <div class='user-name'><%= user.nickname %></div>
            </div>

            <div class='rigth-box'>
              <div class="follow_form">
                <% if current_user.following? user %>
                  <button class="unfollow-btn">
                    <%= link_to "Following", {controller: :users,action: :unfollow,user_id: user.id}, method: :put, class:"unfollow"%>
                  </button>
                <% else %>
                  <button class="follow-btn">
                    <%= link_to "Follow", {controller: :users,action: :follow,user_id: user.id}, method: :put, class:"follow"%>
                  </button>
                <% end %>
              </div>
            </div>
          </div>
        <%end%>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/users/search.html.erb
<div class='friends-wrapper'>

  <%= render "shared/navbar"%>

  <div class='friends-main'>
    <h1 class='my-name'>検索結果</h1>
    <div class='my-friends-data'>
      <h2><%= link_to 'フォロー数', {controller: :users,action: :follow_list,user_id: current_user.id}, class: "follow-path" %>:<%= current_user.follow_count %>　</h2>
      <h2><%= link_to 'フォロワー数', {controller: :users,action: :follower_list,user_id: current_user.id}, class: "follower-path" %>:<%= current_user.followers_count %></h2>
    </div>

    <div class='search-box'>
      <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "ユーザー名を検索する", class: "search-input" %>
        <%= form.submit "Search", class: "search-btn" %>
      <% end %>
    </div>

    <div class='all-user'>
      <% @users.each do |user|%>
        <% if user.id != current_user.id %>
          <div class='each-user'>
            <div class='left-box'>
              <div class='user-img'>
                <%if user.image.present? %>
                  <%= image_tag user.image, class: 'friends-img' %>
                <%else %>
                  <img class='friends-img'>
                <%end %>
              </div>
              <div class='user-name'><%= user.nickname %></div>
            </div>

            <div class='rigth-box'>
              <div class="follow_form">
                <% if current_user.following? user %>
                  <button class="unfollow-btn">
                    <%= link_to "Following", {controller: :users,action: :unfollow,user_id: user.id}, method: :put, class:"unfollow"%>
                  </button>
                <% else %>
                  <button class="follow-btn">
                    <%= link_to "Follow", {controller: :users,action: :follow,user_id: user.id}, method: :put, class:"follow"%>
                  </button>
                <% end %>
              </div>
            </div>
          </div>
        <%end%>
      <% end %>
    </div>

  </div>
</div>

<%= render "shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/navbar" %>

<div class="user-show">
  <div class="user-box">
    <h2 class="profile">
      My Profile
    </h2>
    <div class='user-img-content'>
      <%if current_user.image.present? %>
        <%= image_tag current_user.image ,class:"user-box-img" %>
      <%else %>
        <img class='friends-img'>
      <%end %>
    </div>

    <%=link_to(edit_user_registration_path) do %>
        <button class="edit-btn" >Edit</button>
    <%end%>

    <table class="detail-table">
      <tr>
        <th class="detail-user">ニックネーム</th>
        <td class="detail-value"><%= current_user.nickname %></td>
      </tr>
      <tr>
        <th class="detail-user">フォロー数</th>
        <td class="detail-value"><%= current_user.follow_count %></td>
      </tr>
      <tr>
        <th class="detail-user">フォロワー数</th>
        <td class="detail-value"><%= current_user.followers_count %></td>
      </tr>
      <tr>
        <th class="detail-user">メールアドレス</th>
        <td class="detail-value"><%= current_user.email %></td>
      </tr>
    </table>
  </div>
</div>

  <%= render "shared/footer"%>