config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  
  resources :trainings, only: [:index, :new, :create]
  root "trainings#index"

  put 'users/follow/:user_id',to: 'users#follow'
  put 'users/unfollow/:user_id',to: 'users#unfollow'
  get 'users/follow_list/:user_id',to: 'users#follow_list'
  get 'users/follower_list/:user_id',to:'users#follower_list'
  # フォロー・フォロワーの一覧ページ
end

app/views/shared/_footer.html.erb
<div class='footer-wrapper'>
  Copyright(c) 2020 Sample Inc. All Rights Reserved. Design by Jam.
</div>

app/views/shared/_footer_html.erb
<div class='footer-wrapper'>
  Copyright(c) 2020 Sample Inc. All Rights Reserved. Design by Jam.
</div>

app/views/shared/_header.html.erb
<header>
  <div class="heading">
    <%= link_to image_tag("original_logo.png", class:"logo-icon"), "/" %>
  </div>
  
  <div class="navbar">
    <ul class="nav-lists">
      <% if user_signed_in? %>
        <li><%= link_to 'ライン登録', "#", class: "line" %></li>
        <li><%= link_to 'フレンド', users_path, class: "friends" %></li>
        <li><%= link_to 'マイページ', user_path(current_user), class: "my-page" %></li>
        <li><%= link_to 'トレーニング', new_training_path, class: "training" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <%else%>
        <li><%= link_to 'ログイン', new_user_session_path, class: "sign-in" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <%end%>
    </ul>
  </div>
</header>

app/views/shared/_home.html.erb
<div class='main'>

  <%# 自分のデータ %>
  <div class="my-data">
    <h2 class='title'>My training data</h2>
    <% if @trainings2.present? %>
      <div class="graphs">
        <div class="each-data">
          <h4 class="theme">＜本日のトレーニング＞</h4>
          <%= column_chart @data%>
        </div>

        <div class="each-data">
          <h4 class="theme">＜１週間のトレーニングバランス＞</h4>
          <%= pie_chart @data2, colors: ["#3333cc","#cc3333","#339966","333"],donut: true%>
        </div>

        <div class="each-data">
          <h4 class="theme">＜１週間分の総回数の推移＞</h4>
          <%= line_chart @data3 ,curve: false%>
        </div>
      </div>

    <% else %>
      <div class="data-nothing">
        <h1 class="lets-train">さあ、トレーニングをしましょう！</h1>
        <%=link_to(new_training_path) do %>
          <button class="btn-secondary" >Trainnig!</button>
        <%end%>
      </div>
    <% end %>
  </div>

  <%# フレンドのデータ %>
  <div class="friends-data">
  <h2 class='title'>My friend's data</h2>

    <%if @follows != [] %> 
      <div class="graphs">
        <% @f_datas.each do |data|%>
          <div class="each-data">
            <h4 class="theme">＜１週間分の総回数の推移＞</h4>
            <% friend = @follows[@num]%>
            <div><%= friend.nickname %>さんのデータ</div>
            <% @num += 1 %>
            <%= line_chart data, curve: false %>
          </div>
        <%end%>
        <div class='space'></div>
      </div>
    <%else%>
      <div class="friends-data-nothing">
        <h1 class="lets-make">友達を登録しましょう！</h1>
        <%=link_to(users_path) do %>
          <button class="btn-secondary" >Make Friends!</button>
        <%end%>
      </div> 
      <div class='space'></div>
    <%end%>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class='navbar-wrap'>
  <div class="heading">
    <%= link_to image_tag("original_logo.png", class:"logo-icon"), "/" %>
  </div>
  
  <div class="navbar">
  
    <!--pc-->
    <div class='menu-pc'>
      <ul class='nav-list'>
        <% if user_signed_in? %>
          <li><%= link_to 'MY PAGE', user_path(current_user), class: "my-page" %></li>
          <li><%= link_to 'FRIENDS', users_path, class: "friends" %></li>
          <li><%= link_to 'TRAINING', new_training_path, class: "training" %></li>
          <li><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "log-out" %></li>
        <%else%>
          <li><%= link_to 'LOG IN', new_user_session_path, class: "sign-in" %></li>
          <li><%= link_to 'SIGN UP', new_user_registration_path, class: "sign-up" %></li>
        <%end%>
      </ul>
    </div>

    <!--smafo-->
    <div class='menu-smafo'>
    <input type='checkbox' id='input'>
    <label for='input'><div class='line'></div><div class='line'></div><div class='line'></div></label>
    <div class='content'>

      <ul class='links'>
        <% if user_signed_in? %>
          <li><%= link_to 'MY PAGE', user_path(current_user), class: "my-page" %></li>
          <li><%= link_to 'FRIENDS', users_path, class: "friends" %></li>
          <li><%= link_to 'TRAINING', new_training_path, class: "training" %></li>
          <li><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "log-out" %></li>
        <%else%>
          <li><%= link_to 'LOG IN', new_user_session_path, class: "sign-in" %></li>
          <li><%= link_to 'SIGN UP', new_user_registration_path, class: "sign-up" %></li>
        <%end%>
      </ul>
    </div>
    </div>
  </div>
</div>

app/views/shared/_top.html.erb
<div class='header'>
  <img src='/images/mascle.webp' class='header-img'>
  <div class='slogan'>
    <h1 class='service'>Hajime-Mascle</h1>
    <h2 class='slogan-content'>さあ、コスパ最強の自己投資を始めよう。</h2>
  </div>
</div>

<!-- VISION -->
<section class="sec01">
  <header>
    <h2>VISION</h2>
  </header>
  <div class="vision">
    近頃、新型肺炎の流行により不要な外出は避ける風潮が蔓延している。それに加え人々は日々の業務に追われ平日は自由な時間が比較的少ないのではないだろうか。このように「やらない理由」は幾つでもある。スポーツを愛する者としてこの現状は悲しいものである。そこで私は人々に提唱したい。この窮屈な社会情勢でやり遂げた達成感を身近に感じることができ健康体を保てるツールは何か。それは『筋トレ』であると。
  </div>
</section>
<!-- // VISION -->

<!-- MESSAGE -->
<section class="sec02">
  <div class="wrap">
    <p class="bg"><img src="/images/gym.jpg" class='message-img'></p>
    <div class="txt">
      <div class="vMid">
        <h2>MESSAGE</h2>
        <p>本サービスは、「友達がやっているから自分もやろう」という日本人の特性を活かしたモチベーション管理を念頭に置いています。確かに筋トレは肉体的にも精神的にもタフなものです。しかし想像してみてください。あなたと非常に仲の良い友人がトレーニングしている姿を。それは1人だけではありません。2,3人とトレーニング仲間は増えていきます。あなたも負けていられないでしょう。達成感を分かち合いたいでしょう。ここまで解像度が高くなったなら今すぐ始めましょう。思い立ったが旬です。それではあなたの仲間と刺激し合いながらトレーニングの習慣を確率していきましょう！</p>
      </div>
    </div>
  </div>
</section>
<!-- //MESSAGE -->